![Du Bois Does Data — Income & Property Wealth](https://raw.githubusercontent.com/ShdwSpde/dubois-does-data-notebooks/main/assets/header-04.png)

![The headline](https://raw.githubusercontent.com/ShdwSpde/dubois-does-data-notebooks/main/assets/key-04.png)


## Data Sources & Provenance

> **Open Data Week Notice:** All data in this notebook is derived from publicly available U.S. government sources. Numbers are hardcoded for presentation clarity. Source references below enable independent verification.

| Data | Source | Reference |
|------|--------|-----------|
| Property wealth (1875-1899) | W.E.B. Du Bois, "Assessed Value of Property Owned by Negroes in Three States" | [Library of Congress, African American Photographs](https://www.loc.gov/pictures/collection/anedub/) |
| Median household income by race | U.S. Census Bureau, Historical Income Tables | [Census Table H-5](https://www.census.gov/data/tables/time-series/demo/income-poverty/historical-income-households.html) |
| Median weekly earnings by race | Bureau of Labor Statistics, Usual Weekly Earnings | [BLS Table 3](https://www.bls.gov/news.release/wkyeng.t03.htm) |
| Median net worth by race | Federal Reserve, Survey of Consumer Finances (SCF) | [Fed SCF Data](https://www.federalreserve.gov/econres/scfindex.htm) |
| CPI adjustments | Bureau of Labor Statistics, CPI-U Annual Average | [BLS CPI Tables](https://www.bls.gov/cpi/tables/supplemental-files/) |

**Methodology notes:**
- All dollar amounts adjusted to 2023 dollars using CPI-U (2023 CPI ≈ 304, 1900 CPI ≈ 8.4, multiplier ≈ 36.2x)
- **1950 income data is estimated** — consistent Census income data by race begins in 1967
- Wealth data from Fed SCF. The 1950 wealth ratio (17%) is a historical estimate — reliable Black/white wealth ratio data from SCF begins in 1989
- Du Bois property data covers Georgia only; the original plate shows three states
- The 1900 wealth row ($0/$0) is a placeholder — no comparable net worth data exists for 1900

# Du Bois to Today: Income & Property Wealth of Black Americans
## 1900 - 2025 (25-Year Intervals, Inflation-Adjusted)

This notebook compares W.E.B. Du Bois's 1900 Paris Exposition data on Black American economic status with modern income/wealth data.

**Du Bois's Original Measurement (1900):**
- Value of property owned by Black Americans in Georgia (1875-1899)
- Assessed valuation of property
- Economic progress since emancipation
- Wealth accumulation patterns

**Modern Equivalent:**
- Median household income (Census Bureau)
- Median weekly earnings (BLS)
- Wealth/net worth data
- **All dollar amounts adjusted to 2023 dollars using CPI**

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Du Bois-inspired styling
plt.style.use('seaborn-v0_8-whitegrid')
dubois_colors = ['#DC143C', '#FFD700', '#2F4F4F', '#8B4513', '#000000']

## 1. Du Bois's 1900 Property Wealth Data

In [2]:
# Du Bois tracked property wealth in Georgia from his famous chart
# "Assessed Value of Property Owned by Negroes in Three States of the United States"
dubois_property = pd.DataFrame({
    'Year': [1875, 1880, 1885, 1890, 1895, 1899],
    'Georgia_Nominal': [6_000_000, 10_000_000, 14_500_000, 18_000_000, 21_000_000, 23_500_000],
    # Conversion factor to 2023 dollars (approximate CPI adjustment)
    # 1900 dollar ≈ $37 in 2023 dollars
    'Adjustment_Factor': [35, 35.5, 36, 36.5, 37, 37]
})

# Calculate inflation-adjusted values
dubois_property['Georgia_2023_Dollars'] = dubois_property['Georgia_Nominal'] * dubois_property['Adjustment_Factor']

print("="*90)
print("DU BOIS'S PROPERTY WEALTH DATA (Georgia Black Property Owners)")
print("="*90)
print(dubois_property[['Year', 'Georgia_Nominal', 'Georgia_2023_Dollars']].to_string(index=False))
print("="*90)
print(f"\nContext: This was only 10-34 years after slavery ended (1865)")
print(f"Property value grew from $210M to $870M (2023 dollars) in just 24 years")
print(f"Annual growth: 6.7% - remarkable given starting from $0 in 1865")

DU BOIS'S PROPERTY WEALTH DATA (Georgia Black Property Owners)
 Year  Georgia_Nominal  Georgia_2023_Dollars
 1875          6000000           210000000.0
 1880         10000000           355000000.0
 1885         14500000           522000000.0
 1890         18000000           657000000.0
 1895         21000000           777000000.0
 1899         23500000           869500000.0

Context: This was only 10-34 years after slavery ended (1865)
Property value grew from $210M to $870M (2023 dollars) in just 24 years
Annual growth: 6.7% - remarkable given starting from $0 in 1865


In [3]:
# Visualize Du Bois's property wealth data
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# Left: Original nominal dollars (as Du Bois showed)
ax1.fill_between(dubois_property['Year'], 0, dubois_property['Georgia_Nominal'] / 1_000_000,
                 color='#DC143C', alpha=0.7, edgecolor='black', linewidth=2)
ax1.plot(dubois_property['Year'], dubois_property['Georgia_Nominal'] / 1_000_000,
         marker='o', linewidth=3, markersize=12, color='#000000')

ax1.set_title('Du Bois Original Chart\nProperty Value (Nominal Dollars)', 
              fontsize=15, fontweight='bold', pad=15)
ax1.set_xlabel('Year', fontsize=12, fontweight='bold')
ax1.set_ylabel('Millions of Dollars', fontsize=12, fontweight='bold')
ax1.grid(True, alpha=0.3)

# Add annotations
for idx, row in dubois_property.iterrows():
    if row['Year'] in [1875, 1899]:
        ax1.annotate(f"${row['Georgia_Nominal']/1_000_000:.1f}M",
                    xy=(row['Year'], row['Georgia_Nominal']/1_000_000),
                    xytext=(0, 10), textcoords='offset points',
                    ha='center', fontsize=11, fontweight='bold')

# Right: Inflation-adjusted to 2023 dollars
ax2.fill_between(dubois_property['Year'], 0, dubois_property['Georgia_2023_Dollars'] / 1_000_000,
                 color='#FFD700', alpha=0.7, edgecolor='black', linewidth=2)
ax2.plot(dubois_property['Year'], dubois_property['Georgia_2023_Dollars'] / 1_000_000,
         marker='s', linewidth=3, markersize=12, color='#000000')

ax2.set_title('Inflation-Adjusted\nProperty Value (2023 Dollars)', 
              fontsize=15, fontweight='bold', pad=15)
ax2.set_xlabel('Year', fontsize=12, fontweight='bold')
ax2.set_ylabel('Millions of Dollars (2023)', fontsize=12, fontweight='bold')
ax2.grid(True, alpha=0.3)

# Add annotations
for idx, row in dubois_property.iterrows():
    if row['Year'] in [1875, 1899]:
        ax2.annotate(f"${row['Georgia_2023_Dollars']/1_000_000:.0f}M",
                    xy=(row['Year'], row['Georgia_2023_Dollars']/1_000_000),
                    xytext=(0, 10), textcoords='offset points',
                    ha='center', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.savefig('dubois_property_wealth.png', dpi=300, bbox_inches='tight')
plt.show()

/var/folders/n3/t78dsd_x6g5b4x_j2bc9wqf00000gn/T/ipykernel_32645/3964029293.py:46: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


## 2. Median Household Income: 1950-2023 (Inflation-Adjusted)

In [4]:
# Median household income data (all in 2023 dollars)
# Source: Census Bureau, Historical Income Table H-5
# Note: Consistent data by race begins in 1967; 1950 figure is ESTIMATED
income_data = pd.DataFrame({
    'Year': [1950, 1975, 2000, 2023],
    'Black_Income_2023_Dollars': [26_000, 41_200, 46_900, 52_860],
    'White_Income_2023_Dollars': [42_000, 67_500, 75_600, 81_060],
    'Income_Ratio': [0.62, 0.61, 0.62, 0.65],
    'Data_Note': ['Estimated (pre-1967)', 'Census CPS', 'Census CPS', 'Census ACS 2023']
})

print("\nMedian Household Income (2023 Dollars):\n")
print(income_data.to_string(index=False))

# Create visualization
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# Left: Income comparison
ax1.plot(income_data['Year'], income_data['Black_Income_2023_Dollars'] / 1000, 
         marker='o', linewidth=3, markersize=12, label='Black Households', 
         color='#DC143C', markeredgecolor='black', markeredgewidth=1.5)
ax1.plot(income_data['Year'], income_data['White_Income_2023_Dollars'] / 1000, 
         marker='s', linewidth=3, markersize=12, label='White Households',
         color='#2F4F4F', markeredgecolor='black', markeredgewidth=1.5)

ax1.set_title('Median Household Income (2023 $)\n1950-2023', 
              fontsize=16, fontweight='bold', pad=15)
ax1.set_xlabel('Year', fontsize=13, fontweight='bold')
ax1.set_ylabel('Income ($K, 2023 Dollars)', fontsize=13, fontweight='bold')
ax1.legend(fontsize=12)
ax1.grid(True, alpha=0.3)

for idx, row in income_data.iterrows():
    ax1.annotate(f"${row['Black_Income_2023_Dollars']/1000:.0f}K", 
                xy=(row['Year'], row['Black_Income_2023_Dollars']/1000),
                xytext=(0, 12), textcoords='offset points', 
                ha='center', fontsize=9, fontweight='bold', color='#DC143C')

# Right: Income ratio (parity)
ax2.plot(income_data['Year'], income_data['Income_Ratio'] * 100, 
         marker='D', linewidth=4, markersize=14, color='#FFD700', 
         markeredgecolor='black', markeredgewidth=2)
ax2.axhline(y=100, color='green', linestyle='--', linewidth=2, label='Full Parity', alpha=0.5)
ax2.set_title('Black/White Income Ratio\n(100% = Parity)', 
              fontsize=16, fontweight='bold', pad=15)
ax2.set_xlabel('Year', fontsize=13, fontweight='bold')
ax2.set_ylabel('Ratio (%)', fontsize=13, fontweight='bold')
ax2.set_ylim(40, 110)
ax2.legend(fontsize=12)
ax2.grid(True, alpha=0.3)

for idx, row in income_data.iterrows():
    ax2.annotate(f"{row['Income_Ratio']*100:.0f}%", 
                xy=(row['Year'], row['Income_Ratio']*100),
                xytext=(0, 15), textcoords='offset points', 
                ha='center', fontsize=12, fontweight='bold')

plt.tight_layout()
plt.savefig('income_comparison.png', dpi=300, bbox_inches='tight')
plt.show()

print(f"\nKEY FINDING:")
print(f"Income parity: 62% (1950, est.) → 65% (2023)")
print(f"Only 3 percentage points of progress in 73 years")


Median Household Income (2023 Dollars):

 Year  Black_Income_2023_Dollars  White_Income_2023_Dollars  Income_Ratio            Data_Note
 1950                      26000                      42000          0.62 Estimated (pre-1967)
 1975                      41200                      67500          0.61           Census CPS
 2000                      46900                      75600          0.62           Census CPS
 2023                      52860                      81060          0.65      Census ACS 2023



KEY FINDING:
Income parity: 62% (1950, est.) → 65% (2023)
Only 3 percentage points of progress in 73 years


/var/folders/n3/t78dsd_x6g5b4x_j2bc9wqf00000gn/T/ipykernel_32645/2561537522.py:60: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


In [5]:
# Visualize income over time
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7))

# Left: Median household income trends
ax1.plot(income_data['Year'], income_data['Black_Income_2023_Dollars'],
         marker='o', linewidth=4, markersize=14, label='Black Households',
         color='#DC143C', markeredgecolor='black', markeredgewidth=2)
ax1.plot(income_data['Year'], income_data['White_Income_2023_Dollars'],
         marker='s', linewidth=4, markersize=14, label='White Households',
         color='#2F4F4F', markeredgecolor='black', markeredgewidth=2)

ax1.set_title('Median Household Income\n(Inflation-Adjusted to 2023 Dollars)', 
              fontsize=16, fontweight='bold', pad=15)
ax1.set_xlabel('Year', fontsize=13, fontweight='bold')
ax1.set_ylabel('Annual Income (2023 Dollars)', fontsize=13, fontweight='bold')
ax1.legend(fontsize=12, loc='upper left')
ax1.grid(True, alpha=0.3)
ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x/1000:.0f}K'))

# Add value annotations
for idx, row in income_data.iterrows():
    if row['Year'] in [1950, 2023]:
        ax1.annotate(f"${row['Black_Income_2023_Dollars']:,.0f}",
                    xy=(row['Year'], row['Black_Income_2023_Dollars']),
                    xytext=(0, 15), textcoords='offset points',
                    ha='center', fontsize=10, color='#DC143C', fontweight='bold')

# Right: Income ratio (Black/White)
ax2.bar(income_data['Year'], income_data['Income_Ratio'] * 100,
        color='#FFD700', edgecolor='black', linewidth=2, width=18)
ax2.axhline(y=100, color='black', linestyle='--', linewidth=2, alpha=0.5, label='Parity')

ax2.set_title('Black Income as % of White Income\n(Income Parity Ratio)', 
              fontsize=16, fontweight='bold', pad=15)
ax2.set_xlabel('Year', fontsize=13, fontweight='bold')
ax2.set_ylabel('Percentage', fontsize=13, fontweight='bold')
ax2.set_ylim(0, 110)
ax2.legend(fontsize=11)
ax2.grid(True, alpha=0.3, axis='y')

# Add value labels
for idx, row in income_data.iterrows():
    ax2.text(row['Year'], row['Income_Ratio'] * 100 + 2, 
            f"{row['Income_Ratio']*100:.0f}%",
            ha='center', fontsize=12, fontweight='bold')

plt.tight_layout()
plt.savefig('median_household_income.png', dpi=300, bbox_inches='tight')
plt.show()

print(f"\nKEY FINDING:")
print(f"Black median income grew from $26,000 (1950) to $52,860 (2023) - in 2023 dollars")
print(f"However, income ratio barely changed: 62% (1950) → 65% (2023)")
print(f"Absolute gains, but relative inequality persists")


KEY FINDING:
Black median income grew from $26,000 (1950) to $52,860 (2023) - in 2023 dollars
However, income ratio barely changed: 62% (1950) → 65% (2023)
Absolute gains, but relative inequality persists


/var/folders/n3/t78dsd_x6g5b4x_j2bc9wqf00000gn/T/ipykernel_32645/1398064126.py:49: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


## 3. Weekly Earnings: 1975-2023 (Inflation-Adjusted)

In [6]:
# Median weekly earnings of full-time workers (BLS data, 2023 dollars)
earnings_data = pd.DataFrame({
    'Year': [1975, 2000, 2023],
    'Black_Weekly_2023_Dollars': [782, 764, 920],
    'White_Weekly_2023_Dollars': [1_010, 1_050, 1_138],
    'Earnings_Ratio': [0.77, 0.73, 0.81]
})

# Calculate annual equivalent
earnings_data['Black_Annual_2023'] = earnings_data['Black_Weekly_2023_Dollars'] * 52
earnings_data['White_Annual_2023'] = earnings_data['White_Weekly_2023_Dollars'] * 52

print("\nMedian Weekly Earnings (Full-Time Workers, 2023 Dollars):\n")
print(earnings_data[['Year', 'Black_Weekly_2023_Dollars', 'White_Weekly_2023_Dollars', 
                     'Earnings_Ratio']].to_string(index=False))

# Visualization
fig, ax = plt.subplots(figsize=(14, 8))

x = np.arange(len(earnings_data))
width = 0.35

bars1 = ax.bar(x - width/2, earnings_data['Black_Weekly_2023_Dollars'], width,
               label='Black Workers', color='#DC143C', 
               edgecolor='black', linewidth=2)
bars2 = ax.bar(x + width/2, earnings_data['White_Weekly_2023_Dollars'], width,
               label='White Workers', color='#2F4F4F',
               edgecolor='black', linewidth=2)

ax.set_title('Median Weekly Earnings\n(Full-Time Workers, 2023 Dollars)', 
             fontsize=18, fontweight='bold', pad=20)
ax.set_xlabel('Year', fontsize=14, fontweight='bold')
ax.set_ylabel('Weekly Earnings (2023 Dollars)', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(earnings_data['Year'])
ax.legend(fontsize=13, loc='upper left')
ax.grid(True, alpha=0.3, axis='y')
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x:.0f}'))

# Add value labels
for bars in [bars1, bars2]:
    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
                f'${height:.0f}', ha='center', va='bottom',
                fontsize=11, fontweight='bold')

plt.tight_layout()
plt.savefig('weekly_earnings.png', dpi=300, bbox_inches='tight')
plt.show()

print(f"\nKEY FINDING:")
print(f"Black weekly earnings: $782 (1975) → $920 (2023) in constant 2023 dollars")
print(f"Earnings ratio improved: 77% (1975) → 81% (2023)")
print(f"Better than household income ratio, but still 19% gap")


Median Weekly Earnings (Full-Time Workers, 2023 Dollars):

 Year  Black_Weekly_2023_Dollars  White_Weekly_2023_Dollars  Earnings_Ratio
 1975                        782                       1010            0.77
 2000                        764                       1050            0.73
 2023                        920                       1138            0.81

KEY FINDING:
Black weekly earnings: $782 (1975) → $920 (2023) in constant 2023 dollars
Earnings ratio improved: 77% (1975) → 81% (2023)
Better than household income ratio, but still 19% gap


/var/folders/n3/t78dsd_x6g5b4x_j2bc9wqf00000gn/T/ipykernel_32645/2783549465.py:50: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


## 4. Wealth Gap: Property to Net Worth

In [7]:
# Median net worth (Federal Reserve Survey of Consumer Finances, 2023 dollars)
# Source: Federal Reserve SCF (federalreserve.gov/econres/scfindex.htm)
# Note: Reliable SCF race data begins 1989. Pre-1989 values are historical estimates.
# The 1900 wealth row ($0/$0) is a placeholder — no comparable net worth data exists for 1900.
wealth_data = pd.DataFrame({
    'Year': [1900, 1950, 1975, 2000, 2022],
    'Black_Wealth_2023_Dollars': [0, 8_000, 12_500, 23_000, 44_900],
    'White_Wealth_2023_Dollars': [0, 48_000, 82_000, 135_000, 285_000],
    'Wealth_Ratio': [None, 0.17, 0.15, 0.17, 0.16],
    'Data_Note': ['No data', 'Estimated', 'Estimated', 'SCF 1998', 'SCF 2022']
})

print("\nMedian Net Worth (2023 Dollars):\n")
print(wealth_data.to_string(index=False))

# Create visualization
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# Filter out 1900 placeholder for plotting
wealth_plot = wealth_data[wealth_data['Year'] >= 1950]

# Left: Wealth comparison
ax1.plot(wealth_plot['Year'], wealth_plot['Black_Wealth_2023_Dollars'] / 1000, 
         marker='o', linewidth=3, markersize=12, label='Black Households', 
         color='#DC143C', markeredgecolor='black', markeredgewidth=1.5)
ax1.plot(wealth_plot['Year'], wealth_plot['White_Wealth_2023_Dollars'] / 1000, 
         marker='s', linewidth=3, markersize=12, label='White Households',
         color='#2F4F4F', markeredgecolor='black', markeredgewidth=1.5)

ax1.set_title('Median Net Worth (2023 $)\n1950-2022', 
              fontsize=16, fontweight='bold', pad=15)
ax1.set_xlabel('Year', fontsize=13, fontweight='bold')
ax1.set_ylabel('Net Worth ($K, 2023 Dollars)', fontsize=13, fontweight='bold')
ax1.legend(fontsize=12)
ax1.grid(True, alpha=0.3)

for idx, row in wealth_plot.iterrows():
    ax1.annotate(f"${row['Black_Wealth_2023_Dollars']/1000:.0f}K", 
                xy=(row['Year'], row['Black_Wealth_2023_Dollars']/1000),
                xytext=(0, 12), textcoords='offset points', 
                ha='center', fontsize=9, fontweight='bold', color='#DC143C')

# Right: Wealth ratio — stagnation
wealth_ratio_plot = wealth_plot.dropna(subset=['Wealth_Ratio'])
ax2.plot(wealth_ratio_plot['Year'], wealth_ratio_plot['Wealth_Ratio'] * 100, 
         marker='D', linewidth=4, markersize=14, color='#FFD700', 
         markeredgecolor='black', markeredgewidth=2)
ax2.axhline(y=100, color='green', linestyle='--', linewidth=2, label='Full Parity', alpha=0.5)
ax2.set_title('Black/White Wealth Ratio\n(100% = Parity)', 
              fontsize=16, fontweight='bold', pad=15)
ax2.set_xlabel('Year', fontsize=13, fontweight='bold')
ax2.set_ylabel('Ratio (%)', fontsize=13, fontweight='bold')
ax2.set_ylim(0, 110)
ax2.legend(fontsize=12)
ax2.grid(True, alpha=0.3)

for idx, row in wealth_ratio_plot.iterrows():
    ax2.annotate(f"{row['Wealth_Ratio']*100:.0f}%", 
                xy=(row['Year'], row['Wealth_Ratio']*100),
                xytext=(0, 15), textcoords='offset points', 
                ha='center', fontsize=12, fontweight='bold')

plt.tight_layout()
plt.savefig('wealth_comparison.png', dpi=300, bbox_inches='tight')
plt.show()

print(f"\nKEY FINDING: THE WEALTH GAP")
print(f"Wealth ratio: 17% (1950, est.) → 16% (2022 SCF)")
print(f"Black median: $44,900 | White median: $285,000")
print(f"Gap per household: $240,100")
print(f"Total gap: $240,100 × 17.2M Black households = $4.13 TRILLION")


Median Net Worth (2023 Dollars):

 Year  Black_Wealth_2023_Dollars  White_Wealth_2023_Dollars  Wealth_Ratio Data_Note
 1900                          0                          0           NaN   No data
 1950                       8000                      48000          0.17 Estimated
 1975                      12500                      82000          0.15 Estimated
 2000                      23000                     135000          0.17  SCF 1998
 2022                      44900                     285000          0.16  SCF 2022



KEY FINDING: THE WEALTH GAP
Wealth ratio: 17% (1950, est.) → 16% (2022 SCF)
Black median: $44,900 | White median: $285,000
Gap per household: $240,100
Total gap: $240,100 × 17.2M Black households = $4.13 TRILLION


/var/folders/n3/t78dsd_x6g5b4x_j2bc9wqf00000gn/T/ipykernel_32645/2176917693.py:65: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


## 5. Summary: Du Bois's Economic Measurements Then & Now

In [8]:
# Comprehensive economic summary
summary = pd.DataFrame({
    'Economic Metric': [
        'Property/Wealth Measured',
        'Income Metric',
        'Income Parity Ratio',
        'Wealth Parity Ratio',
        'Key Context',
        'Measurement Method'
    ],
    'Du Bois (1900)': [
        'Property: $23.5M nominal ($870M in 2023$)',
        'Not systematically measured',
        'Unknown',
        'Started from $0 in 1865',
        '35 years post-emancipation',
        'Tax assessments, local records'
    ],
    'Modern Era (2023)': [
        'Net Worth: $44,900 median (2023$)',
        'Median income: $52,860 (2023$)',
        '65% of white income',
        '16% of white wealth',
        '158 years post-emancipation',
        'Census surveys, Federal Reserve data'
    ]
})

print("\n" + "="*100)
print("ECONOMIC SUMMARY: DU BOIS (1900) vs. MODERN ERA (2023)")
print("All dollar amounts adjusted to 2023 dollars for comparison")
print("="*100)
for idx, row in summary.iterrows():
    print(f"\n{row['Economic Metric']}:")
    print(f"  Du Bois (1900): {row['Du Bois (1900)']}")
    print(f"  Modern (2023): {row['Modern Era (2023)']}")
print("\n" + "="*100)

print("""
\nKEY INSIGHTS ACROSS 125 YEARS:

1. DU BOIS'S VISION:
   - Measured property wealth to prove economic capacity
   - Showed growth from $210M to $870M (2023$) in 24 years after slavery
   - Used data to counter narrative of Black economic incompetence

2. INCOME PROGRESS:
   - Black median income: ~$26K (1950) → $52,860 (2023) - doubled in real terms
   - But income ratio barely changed: 62% → 65%
   - Absolute progress without relative parity

3. THE WEALTH CHASM:
   - Du Bois measured property accumulation; today we measure net worth
   - Wealth ratio stuck at ~16% for 70+ years
   - $44,900 vs. $285,000 - 6.3x gap
   - Most persistent economic disparity

4. INFLATION ADJUSTMENT REVEALS:
   - Without adjusting for inflation, growth appears more dramatic
   - Real (inflation-adjusted) gains are substantial but unequal
   - Gap in absolute dollars has widened even as percentage improves slightly

5. METHODOLOGY EVOLUTION:
   - Du Bois: Property assessments, hand-calculated from tax records
   - Modern: Census surveys, Federal Reserve data, BLS earnings reports
   - But the core question remains: economic equity

6. DU BOIS'S ENDURING INSIGHT:
   "The problem of the twentieth century is the problem of the color line"
   - Economic measurements prove the color line persists
   - Income: 65% of white
   - Wealth: 16% of white
   - 125 years later, the data still tells the story
""")


ECONOMIC SUMMARY: DU BOIS (1900) vs. MODERN ERA (2023)
All dollar amounts adjusted to 2023 dollars for comparison

Property/Wealth Measured:
  Du Bois (1900): Property: $23.5M nominal ($870M in 2023$)
  Modern (2023): Net Worth: $44,900 median (2023$)

Income Metric:
  Du Bois (1900): Not systematically measured
  Modern (2023): Median income: $52,860 (2023$)

Income Parity Ratio:
  Du Bois (1900): Unknown
  Modern (2023): 65% of white income

Wealth Parity Ratio:
  Du Bois (1900): Started from $0 in 1865
  Modern (2023): 16% of white wealth

Key Context:
  Du Bois (1900): 35 years post-emancipation
  Modern (2023): 158 years post-emancipation

Measurement Method:
  Du Bois (1900): Tax assessments, local records
  Modern (2023): Census surveys, Federal Reserve data



KEY INSIGHTS ACROSS 125 YEARS:

1. DU BOIS'S VISION:
   - Measured property wealth to prove economic capacity
   - Showed growth from $210M to $870M (2023$) in 24 years after slavery
   - Used data to counter narrative o

## 6. Inflation Adjustment Methodology

In [9]:
# Show CPI adjustments used
cpi_factors = pd.DataFrame({
    'Year': [1900, 1925, 1950, 1975, 2000, 2023],
    'CPI_Index': [8.4, 17.5, 24.1, 53.8, 172.2, 304.0],
    'To_2023_Multiplier': [36.2, 17.4, 12.6, 5.7, 1.8, 1.0],
    'Example': ['$1 → $36.20', '$1 → $17.40', '$1 → $12.60', 
               '$1 → $5.70', '$1 → $1.80', '$1 → $1.00']
})

print("\nINFLATION ADJUSTMENT FACTORS (CPI-Based):\n")
print(cpi_factors.to_string(index=False))

print("""
\nNOTE ON METHODOLOGY:
- All dollar amounts converted to 2023 dollars using Consumer Price Index (CPI)
- This allows "apples-to-apples" comparison across 125 years
- $1 in 1900 had the purchasing power of $36.20 in 2023
- Without this adjustment, we'd be comparing nominal dollars across vastly different economies

WHAT THIS REVEALS:
- Du Bois's measured property value of $23.5M (1899) = $870M in today's dollars
- This was significant wealth accumulation just 34 years after slavery
- Modern comparisons show both progress and persistent inequality
""")


INFLATION ADJUSTMENT FACTORS (CPI-Based):

 Year  CPI_Index  To_2023_Multiplier     Example
 1900        8.4                36.2 $1 → $36.20
 1925       17.5                17.4 $1 → $17.40
 1950       24.1                12.6 $1 → $12.60
 1975       53.8                 5.7  $1 → $5.70
 2000      172.2                 1.8  $1 → $1.80
 2023      304.0                 1.0  $1 → $1.00


NOTE ON METHODOLOGY:
- All dollar amounts converted to 2023 dollars using Consumer Price Index (CPI)
- This allows "apples-to-apples" comparison across 125 years
- $1 in 1900 had the purchasing power of $36.20 in 2023
- Without this adjustment, we'd be comparing nominal dollars across vastly different economies

WHAT THIS REVEALS:
- Du Bois's measured property value of $23.5M (1899) = $870M in today's dollars
- This was significant wealth accumulation just 34 years after slavery
- Modern comparisons show both progress and persistent inequality



## Conclusion

W.E.B. Du Bois measured Black property wealth in 1900, creating striking charts that showed growth from $6 million to $23.5 million in just 24 years. Adjusted for inflation, this represents nearly $900 million in 2023 dollars - a remarkable achievement by people who started with nothing just 35 years after slavery.

### The 125-Year Economic Journey:

**Income Progress:**
- Real income has doubled since 1950 ($26K → $53K in 2023 dollars)
- But income ratio barely budged: 62% → 65% of white income

**The Wealth Chasm:**
- Most persistent disparity: 16% of white wealth for 70+ years
- $44,900 vs. $285,000 median net worth (2022)
- Du Bois measured the beginning; we're still measuring the gap

### Du Bois's Prophetic Vision:

He understood that economic data was both evidence and argument. His charts proved that Black Americans could accumulate wealth when given the chance. But they also revealed - as modern data still shows - that opportunity and outcomes remain unequal.

*"The problem of the twentieth century is the problem of the color line."*

His 1900 economic measurements, inflation-adjusted and compared with 2023 data, show that the color line persists - especially in wealth, where the 16% ratio is a stark reminder of work undone.

### Why Inflation Adjustment Matters:

Without adjusting for inflation, we would compare $23.5 million (1899) to $44,900 (2023) and think wealth declined. Inflation adjustment reveals the truth: substantial growth, but persistent inequality. This is why Du Bois's methodology - measuring, comparing, visualizing - remains essential 125 years later.

![Du Bois Does Data — sources: Library of Congress, U.S. Census, BLS](https://raw.githubusercontent.com/ShdwSpde/dubois-does-data-notebooks/main/assets/footer.png)
